CREATE TABLE categories
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name   VARCHAR(50) NOT NULL,
    active BOOLEAN     NOT NULL,

    CONSTRAINT uc_categories_name UNIQUE (name)
);