CREATE TABLE orders
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50) NOT NULL,
    description VARCHAR(255),
    price       DECIMAL     NOT NULL,
    stock       INTEGER     NOT NULL,
    active      BOOLEAN     NOT NULL,
    createdAt   DATE        NOT NULL,
    updatedAt   DATE        NOT NULL,
    category_id BIGINT      NOT NULL,


    CONSTRAINT uc_products_name UNIQUE (name),
    CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories (id)
);