package com.leandroftm.ordermanagement.order_management_api.exception.enums;

public enum ErrorCode {
    UNEXPECTED_ERROR,
    VALIDATION_ERROR,
    INVALID_CREDENTIALS,
    CATEGORY_NOT_FOUND,
    CATEGORY_ALREADY_EXISTS,
    CATEGORY_NAME_ALREADY_EXISTS,
    CATEGORY_NOT_EMPTY,
    CATEGORY_ALREADY_INACTIVE,
    CATEGORY_ALREADY_ACTIVE,
    INVALID_CATEGORY_NAME,
    ORDER_NOT_FOUND,
    PRODUCT_NOT_FOUND,
    PRODUCT_CATEGORY_MISMATCH,
    PRODUCT_ALREADY_EXISTS,
    PRODUCT_ALREADY_INACTIVE,
    PRODUCT_ALREADY_ACTIVE,
    INVALID_PRODUCT_PRICE,
    INVALID_STOCK_VALUE,
    INVALID_STOCK_AMOUNT_VALUE
}
