CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      VARCHAR(255) NOT NULL,
    password   VARCHAR(255)  NOT NULL,
    enabled    BOOLEAN      NOT NULL,
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP    NOT NULL,
    role       VARCHAR(20)  NOT NULL,

    CONSTRAINT uc_users_email UNIQUE (email)
);