CREATE TABLE orders
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    total_amount DECIMAL NOT NULL,
    description VARCHAR(255),
    created_at   DATE        NOT NULL,
    updated_at   DATE        NOT NULL,
    status VARCHAR(20) NOT NULL,
    user_id BIGINT NOT NULL,

    CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES users (id)
);