CREATE TABLE order_items
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantity            INTEGER NOT NULL,
    unit_price          DECIMAL NOT NULL,
    discount_percentage DECIMAL NOT NULL,
    order_id            BIGINT  NOT NULL,
    product_id          BIGINT  NOT NULL,

    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products (id)
);